version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ignis-backend-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13xtti8er3wuy"
s3_prefix = "ignis-backend-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"dev\""
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "ignis-backend-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13xtti8er3wuy"
s3_prefix = "ignis-backend-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"prod\""
image_repositories = []
