AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ignis-backend

  SAM Template for ignis-backend

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Environment in which the application will be deployed. Allowed values [dev, prod]

Mappings:
  EnvMapping:
    dev:
      dbHost: "{{resolve:ssm:SUPBASE_DEV_HOST}}"
      dbName: "{{resolve:ssm:SUPBASE_DEV_NAME}}"
      dbUser: "{{resolve:ssm:SUPBASE_DEV_USERNAME}}"
      dbPass: "{{resolve:ssm:SUPBASE_DEV_PASSWORD}}"
      dbPort: "{{resolve:ssm:SUPBASE_DEV_PORT}}"
      secretkey: "{{resolve:ssm:DEV_SECRET_KEY}}"
      supersecretkey: "{{resolve:ssm:DEV_SUPER_SECRET_KEY}}"
      bucket: "{{resolve:ssm:DEV_AWS_BUCKET}}"
      region: "{{resolve:ssm:DEV_AWS_REGION}}"

    prod:
      dbHost: "{{resolve:ssm:IGNIS_PROD_HOST}}"
      dbName: "{{resolve:ssm:IGNIS_PROD_NAME}}"
      dbUser: "{{resolve:ssm:IGNIS_PROD_USERNAME}}"
      dbPass: "{{resolve:ssm:IGNIS_PROD_PASSWORD}}"
      dbPort: "{{resolve:ssm:IGNIS_PROD_PORT}}"
      secretkey: "{{resolve:ssm:DEV_SECRET_KEY}}"
      supersecretkey: "{{resolve:ssm:DEV_SUPER_SECRET_KEY}}"
      bucket: "{{resolve:ssm:IGNIS_PROD_BUCKET}}"
      region: "{{resolve:ssm:IGNIS_PROD_REGION}}"

Globals:
  Function:
    Timeout: 180
    Handler: app.lambdaHandler
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        DB_HOST: !FindInMap [EnvMapping, !Ref Env, dbHost]
        DB_NAME: !FindInMap [EnvMapping, !Ref Env, dbName]
        DB_USER: !FindInMap [EnvMapping, !Ref Env, dbUser]
        DB_PASS: !FindInMap [EnvMapping, !Ref Env, dbPass]
        DB_PORT: !FindInMap [EnvMapping, !Ref Env, dbPort]
        SECRET_KEY: !FindInMap [EnvMapping, !Ref Env, secretkey]
        SUPER_SECRET_KEY: !FindInMap [EnvMapping, !Ref Env, supersecretkey]
        BUCKET: !FindInMap [EnvMapping, !Ref Env, bucket]
        REGION: !FindInMap [EnvMapping, !Ref Env, region]
        ResetVariable: 0 # Used for cold start!

Resources:
  ############ LAMBDA FUNCTIONS ############

  #ClientAuth API to authenticate ClientUsers
  ClientAuthAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/clientauth/
      Events:
        ClientAuthApi:
          Type: Api
          Properties:
            Path: /clientauth/{proxy+}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #TechAuth API to authenticate TechAppUsers
  TechAuthAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/TechnicianAppAPIs/TechAuth/
      Events:
        TechAuthApi:
          Type: Api
          Properties:
            Path: /techauth/{proxy+}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #SuperAuth API to authenticate superadmins
  SuperAuthAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/superadminapis/superauth/
      Events:
        SuperAuthApi:
          Type: Api
          Properties:
            Path: /superauth/{proxy+}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #VerifyCLient API to verify client
  VerifyClientAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/superadminapis/verifyclient/
      Events:
        VerifyClientApi:
          Type: Api
          Properties:
            Path: /verifyclient
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #CommonFields API to update and get common fields for devicetypes
  CommonFieldsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/superadminapis/CommonFields/
      Events:
        CommonFieldsApi:
          Type: Api
          Properties:
            Path: /commonfields
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #AHJpdf API to manage AHJ Report PDF Fields
  AHJpdfAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/superadminapis/AHJpdf/
      Events:
        AHJpdfApi:
          Type: Api
          Properties:
            Path: /AHJpdf
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ContractValidityCheck API to check contract status
  ContractValidityCheckAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/ContractValidityCheck/
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(12 13,18 * * ? *)
      Layers:
        - !Ref GeneralDependenciesLayer

  #Dashboard API to get Dashboard Data
  DashboardAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/TechnicianAppAPIs/Dashboard/
      Events:
        DashboardApi:
          Type: Api
          Properties:
            Path: /dashboard
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #TechWorkOrders API to View Work Orders in Technician App
  TechWorkOrdersAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/TechnicianAppAPIs/TechWorkOrders/
      Events:
        TechWorkOrdersApi:
          Type: Api
          Properties:
            Path: /techworkorders
            Method: ANY
        TechWorkOrderApi:
          Type: Api
          Properties:
            Path: /techworkorders/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ITM API to View and Execute ITM Work Orders in Technician App
  ITMAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/TechnicianAppAPIs/ITM/
      Events:
        ITMsApi:
          Type: Api
          Properties:
            Path: /ITM
            Method: ANY
        ITMApi:
          Type: Api
          Properties:
            Path: /ITM/{id}
            Method: ANY
      Policies:
        - S3CrudPolicy:
            BucketName: ignis-dev
      Layers:
        - !Ref GeneralDependenciesLayer

  #ITMView API to View and Reset ITM Results
  ITMViewAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/TechnicianAppAPIs/ITMView/
      Events:
        ITMViewsApi:
          Type: Api
          Properties:
            Path: /ITMView
            Method: ANY
        ITMViewApi:
          Type: Api
          Properties:
            Path: /ITMView/{id}
            Method: ANY
      Policies:
        - S3CrudPolicy:
            BucketName: ignis-dev
      Layers:
        - !Ref GeneralDependenciesLayer

  #AssetTagging API to View and Reset ITM Results
  AssetTaggingAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/TechnicianAppAPIs/AssetTagging/
      Events:
        AssetTaggingsApi:
          Type: Api
          Properties:
            Path: /AssetTagging
            Method: ANY
        AssetTaggingApi:
          Type: Api
          Properties:
            Path: /AssetTagging/{id}
            Method: ANY
      Policies:
        - S3CrudPolicy:
            BucketName: ignis-dev
      Layers:
        - !Ref GeneralDependenciesLayer

  #DropDown API to Add/View/Modify/Delete dropdowns
  DropdownAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/dropdown/
      Events:
        DropdownApi:
          Type: Api
          Properties:
            Path: /dropdown/{proxy+}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #Clients API to Add/View/Modify/Delete Clients
  ClientsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/superadminapis/clients/
      Events:
        ClientsApi:
          Type: Api
          Properties:
            Path: /clients
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #Notifications API to Add/View/Modify/Delete buildings
  NotificationsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/notifications/
      Events:
        NotificationsApi:
          Type: Api
          Properties:
            Path: /notifications
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #FileUpload API to generate link to upload file
  FileUploadAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/FileUpload/
      Events:
        FileUploadApi:
          Type: Api
          Properties:
            Path: /fileupload
            Method: ANY
      Policies:
        - S3CrudPolicy:
            BucketName: ignis-dev
      Layers:
        - !Ref GeneralDependenciesLayer

  #Coordinates API to get Coordinate from QND95 to Lat&Long
  CoordinatesAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/coordinates/
      Events:
        CoordinatesApi:
          Type: Api
          Properties:
            Path: /coordinates
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #SuperAdmin API to Add/View/Modify/Delete SuperAdmins
  SuperAdminsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/superadminapis/SuperAdmins/
      Events:
        SuperAdminsApi:
          Type: Api
          Properties:
            Path: /superadmins
            Method: ANY
        SuperAdminApi:
          Type: Api
          Properties:
            Path: /superadmins/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientTeams API to Add/View/Modify/Delete ClientTeams
  ClientTeamsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientTeams/
      Events:
        ClientTeamsApi:
          Type: Api
          Properties:
            Path: /clientteams
            Method: ANY
        ClientTeamApi:
          Type: Api
          Properties:
            Path: /clientteams/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientUsers API to Add/View/Modify/Delete ClientUsers
  ClientUsersAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientUsers/
      Events:
        ClientUsersApi:
          Type: Api
          Properties:
            Path: /clientusers
            Method: ANY
        ClientUserApi:
          Type: Api
          Properties:
            Path: /clientusers/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientWorkOrders API to Add/View/Modify/Delete ClientWorkOrders
  ClientWorkOrdersAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientWorkOrders/
      Events:
        ClientWorkOrdersApi:
          Type: Api
          Properties:
            Path: /clientworkorders
            Method: ANY
        ClientWorkOrderApi:
          Type: Api
          Properties:
            Path: /clientworkorders/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientMessages API to Add/View/Modify/Delete ClientMessages
  ClientMessagesAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientMessages/
      Events:
        ClientMessagesApi:
          Type: Api
          Properties:
            Path: /clientmessages/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientRoles API to Add/View/Modify/Delete ClientRoles
  ClientRolesAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientRoles/
      Events:
        ClientRolesApi:
          Type: Api
          Properties:
            Path: /clientroles
            Method: ANY
        ClientRoleApi:
          Type: Api
          Properties:
            Path: /clientroles/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientEmployees API to Add/View/Modify/Delete ClientEmployees
  ClientEmployeesAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientEmployees/
      Events:
        ClientEmployeesApi:
          Type: Api
          Properties:
            Path: /clientemployees
            Method: ANY
        ClientEmployeeApi:
          Type: Api
          Properties:
            Path: /clientemployees/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientNotifications API to Add/View/Modify/Delete ClientNotifications
  ClientNotificationsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientNotifications/
      Events:
        ClientNotificationsApi:
          Type: Api
          Properties:
            Path: /clientnotifications
            Method: ANY
        ClientNotificationApi:
          Type: Api
          Properties:
            Path: /clientnotifications/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientResources API to Add/View/Modify/Delete ClientResources
  ClientResourcesAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientResources/
      Events:
        ClientResourcesApi:
          Type: Api
          Properties:
            Path: /clientresources
            Method: ANY
        ClientResourceApi:
          Type: Api
          Properties:
            Path: /clientresources/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientControllers API to Add/View/Modify/Delete ClientControllers
  ClientControllersAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientControllers/
      Events:
        ClientControllersApi:
          Type: Api
          Properties:
            Path: /clientcontrollers
            Method: ANY
        ClientControllerApi:
          Type: Api
          Properties:
            Path: /clientcontrollers/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientAssets API to Add/View/Modify/Delete ClientAssets
  ClientAssetsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientAssets/
      Events:
        ClientAssetsApi:
          Type: Api
          Properties:
            Path: /clientassets
            Method: ANY
        ClientAssetApi:
          Type: Api
          Properties:
            Path: /clientassets/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientMassUpdate API to Add/View/Modify/Delete ClientMassUpdate
  ClientMassUpdateAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientMassUpdate/
      Events:
        ClientMassUpdateApi:
          Type: Api
          Properties:
            Path: /clientMassUpdate
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientBuildings API to Add/View/Modify/Delete ClientBuildings
  ClientBuildingsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientBuildings/
      Events:
        ClientBuildingsApi:
          Type: Api
          Properties:
            Path: /clientbuildings
            Method: ANY
        ClientBuildingApi:
          Type: Api
          Properties:
            Path: /clientbuildings/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientContracts API to Add/View/Modify/Delete ClientContracts
  ClientContractsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientContracts/
      Events:
        ClientContractsApi:
          Type: Api
          Properties:
            Path: /clientcontracts
            Method: ANY
        ClientContractApi:
          Type: Api
          Properties:
            Path: /clientcontracts/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #ClientSystems API to Add/View/Modify/Delete ClientSystems
  ClientSystemsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/clientapis/ClientSystems/
      Events:
        ClientSystemsApi:
          Type: Api
          Properties:
            Path: /clientsystems
            Method: ANY
        ClientSystemApi:
          Type: Api
          Properties:
            Path: /clientsystems/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #SystemMaster API to Add/View/Modify/Delete SystemMaster
  SystemMasterAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/superadminapis/SystemMaster/
      Events:
        SystemMastersApi:
          Type: Api
          Properties:
            Path: /systemmaster
            Method: ANY
        SystemMasterApi:
          Type: Api
          Properties:
            Path: /systemmaster/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #DeviceMaster API to Add/View/Modify/Delete DeviceMaster
  DeviceMasterAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/superadminapis/DeviceMaster/
      Events:
        DeviceMastersApi:
          Type: Api
          Properties:
            Path: /devicemaster
            Method: ANY
        DeviceMasterApi:
          Type: Api
          Properties:
            Path: /devicemaster/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #Procedures API to Add/View/Modify/Delete Procedures
  ProceduresAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/superadminapis/Procedures/
      Events:
        ProceduresApi:
          Type: Api
          Properties:
            Path: /procedure
            Method: ANY
        ProcedureApi:
          Type: Api
          Properties:
            Path: /procedure/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  #AHJform API to Add/View/Modify/Delete AHJs
  AHJformAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/superadminapis/AHJform/
      Events:
        AHJformsApi:
          Type: Api
          Properties:
            Path: /ahjform
            Method: ANY
        AHJformApi:
          Type: Api
          Properties:
            Path: /ahjform/{id}
            Method: ANY
      Layers:
        - !Ref GeneralDependenciesLayer

  ############ DEPENDENCIES ############

  #Common Dependencies
  GeneralDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dependencies
      Description: Common Dependencies
      ContentUri: dependencies/general/
      CompatibleRuntimes:
        - nodejs14.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
